### ISSUE TITLE
How to edit the loadmorecell

### ISSUE THREAD

**Issue by aakarshsasi** [salmaanahmed/PaginatedTableView#11]
I want to customise the loadmorecell. How can i do that in the cellForRowAt method?

**Comment by salmaanahmed** [comment]
Hey @dnawarrior,
Currently this library do not support customizing loadMoreCell, so it is not possible for now.
Anyhow this seems to be good idea, if you want you can make a PR for this feature.

**Comment by ratulSharker** [comment]
@dnawarrior I have a simillar implementation, which supports custom **Load More** cell. Can take a look [here](https://github.com/ratulSharker/TableviewPaginator).

**Comment by salmaanahmed** [comment]
@aakarshsasi you can see this issue https://github.com/salmaanahmed/PaginatedTableView/issues/15
