### ISSUE TITLE
How to customise the bottom view where the activity indicator is showing?

### ISSUE THREAD

**Issue by sajib-ghosh-iOS** [salmaanahmed/PaginatedTableView#15]
I want to edit the bottom view colour where the activity indicator is showing, is there any way to do it?

Thanks in advance!

**Comment by salmaanahmed** [comment]
Hey @sajib-ghoshInnofied 

It is not currently supported but what you can do is, get last cell when tableView is loading
`let cell = tableView.cellForRow(at: indexPath)`

And then you can change the background colour of `cell`

FYI: You should look for first cell of last section
i.e. `let indexPath = IndexPath(row: 0, section: tableView.sections - 1)`

I hope it helps.

**Comment by sajib-ghosh-iOS** [comment]
Thanks. it helps.
