### ISSUE TITLE
How to take action after pull to refresh?

### ISSUE THREAD

**Issue by sajib-ghosh-iOS** [salmaanahmed/PaginatedTableView#16]
Hi,

Thanks for making this awesome library, its really awesome.

I just wanted to know how I will take action after pull to refresh? I want to do some customisation after pull to refresh. How will I achieve this?

Thanks in advance!

**Comment by salmaanahmed** [comment]
Hey @sajib-ghoshInnofied 

Do you see **step 4** in readme?
That is where loading starts and you can do whatever you want.
And when you fire completion, it will stop the loader.

I hope it helps.

**Comment by sajib-ghosh-iOS** [comment]
Thanks for your reply.

The loadMore method doesn't get called after pull to refresh. 
Initially it gets called when I write tableView.loadData(refresh: true) in viewDidLoad but after pull to refresh it doesn't work.

Any idea why it's happening?

**Comment by salmaanahmed** [comment]
It will be easier if you can share the code.

I assume you are not calling `onSuccess?(true)` in the end of `func loadMore`.
See example [here](https://github.com/salmaanahmed/PaginatedTableView/blob/9ee574965f03d286070eb42110ae4e71bdd42317/Example/PaginatedTableView/ViewController.swift#L61)
