### ISSUE TITLE
How to attach UISearchController

### ISSUE THREAD

**Issue by rinaldihno** [salmaanahmed/PaginatedTableView#5]
Hi Ahmed,
I'd like to attach a UISearchController to a PaginatedTableView, is it the right way ?

In delegate search result update method, save search text for future call of load data, and send a loadData with refresh true.

func updateSearchResults(for searchController: UISearchController) {
        if let searchText = searchController.searchBar.text {
            
            self.currentSearchText = searchText
            tableView.loadData(refresh: true)
          
        }
    }

Use currentSearchText in loadMore ?\

Thanks for help

**Comment by salmaanahmed** [comment]
Yes that is how you will do this, I hope it works fine.
