### ISSUE TITLE
Delegate issue

### ISSUE THREAD

**Issue by aakarshsasi** [salmaanahmed/PaginatedTableView#8]
Cannot assign value of type 'ViewController' to type 'PaginatedTableViewDataSource?'
Insert ' as! PaginatedTableViewDataSource'
When I insert as it crashes

**Comment by salmaanahmed** [comment]
You have to assign `paginatedDataSource` instead of `PaginatedTableViewDataSource` `tableView.paginatedDataSource = self`
and also do make sure that you conform your `ViewController` with `PaginatedTableViewDataSource`

**Comment by aakarshsasi** [comment]
Thank you
